### ISSUE TITLE
SVG Decoder

### ISSUE THREAD

**Issue by jwittenbach** [elm-lang/svg#14]
Is there any way to decode an SVG file (fetched as text) into the SVG nodes in this package? If not, are there any plans to add this?

**Comment by evancz** [comment]
There's no SVG parser as part of this library. Can you outline your usage scenario? We don't add features without a concrete example of why it's a good idea.

**Comment by jwittenbach** [comment]
Sure thing. I've been playing around with using this package to programmatically create SVG, and it works great. But I frequently create SVG content offline which I then want to use in a webpage. In JS, I use XHR to fetch it. Then I can add event handlers finally add it as an `<svg>` node. In Elm, the best I can do is fetch it as text, but then I have no way to parse it into a form that would be useable by this package. Seems like it might be a generally useful piece of functionality, similar to the great JSON decoding tools that exist in Elm.

**Comment by evancz** [comment]
Sorry about the robot, it got out of whack for a little while!

It sounds like an XML decoder may be the thing you are looking for? It should cover this case right? Like, someone could make an SVG specific thing on top of an XML decoder.
