### ISSUE TITLE
Stringly typed

### ISSUE THREAD

**Issue by SwiftsNamesake** [elm-lang/svg#15]
Wouldn't it be better for a statically typed language such as Elm to encode attribute values with appropriate types rather than using strings for most things?

I'm thinking especially of paths being defined as strings.

**Comment by evancz** [comment]
From the README https://github.com/elm-lang/svg/blob/master/README.md

> **Note:** This library aims to be the most basic API. In some cases it is possible to use union types to build nicer abstractions, but this starts bringing personal taste into things and has some additional maintainance cost if the underlying spec changes. I think it is best to build such abstractions on top of this library as a separate package.
