### ISSUE TITLE
special-case many nodes

### ISSUE THREAD

**Issue by iqualfragile** [elm-lang/svg#18]
having to import and use tons of "x" "x1"s is extremly tedious, it would be better to provide special functions, which take, for example for a circle its center coordinates and radius (+generic attributes +child nodes).

**Comment by evancz** [comment]
As it says in [the readme](https://github.com/elm-lang/svg/blob/master/README.md):

> **Note:** This library aims to be the most basic API. In some cases it is possible to use union types to build nicer abstractions, but this starts bringing personal taste into things and has some additional maintainance cost if the underlying spec changes. I think it is best to build such abstractions on top of this library as a separate package.
