### ISSUE TITLE
Installed version through elm package doesn't export Svg.Events.on

### ISSUE THREAD

**Issue by Shump** [elm-lang/svg#4]
I saw that Svg.Events.on was added to exported functions in b0ed4d9e55054e4d5f0d8ebdda481651cda89982 however, the version installed through `elm package install elm-lang/svg` does not export the function.

I need it to define my own decoder for onMouseMove events. Or is there another way to obtain the coordinates otherwise?

**Comment by evancz** [comment]
It should be in the public API now!
