### ISSUE TITLE
svg 1.1.1 line and text don't seem to match documentation

### ISSUE THREAD

**Issue by rhetr** [elm-lang/svg#8]
i'm trying to write a function that takes an int and outputs svg text like so:

```
drawNum num = 
    text' [ x 30, y 30 ] [ text (toString num) ]
```

the [documentation](http://package.elm-lang.org/packages/elm-lang/svg/1.1.1/Svg#text') says `text'` outputs `Svg Msg` so I wrote the type annotation like 
```
drawNum : Int -> Svg Msg
```

but i keep getting this error:

```
The type annotation is saying:

    Int -> Svg a

But I am inferring that the definition has this type:

    Float -> Svg a
```

I checked `elm-repl` to see what the type annotation of `Svg.text'` looks like and saw this:
```
> import Svg
> Svg.text'
<function> : List (Svg.Attribute a) -> List (Svg.Svg a) -> Svg.Svg a
```
I'm getting similar results for `text` too.. I guess I'm not understanding exactly what `Svg a` is in relation to `Svg msg`? Also why is elm insisting that I am passing in a `Float`?

**Comment by jvoigtlaender** [comment]
Where do you see that error message? I don't think it actually occurs for the program you claim it is occurring for? At least, on http://elm-lang.org/try the test program
```elm
import Svg exposing (..)
import Svg.Attributes exposing (..)

type Msg = Msg

drawNum : Int -> Svg Msg
drawNum num = 
    text' [ x 30, y 30 ] [ text (toString num) ]
```
gives a completely different message than the one you show.

**Comment by rhetr** [comment]
oh I see, I wasn't properly declaring `type Msg = Msg`. I'm still getting the error I mentioned though using this code:

```elm
import Html exposing (div, h1)
import Svg exposing (..)
import Svg.Attributes exposing (..)

type Msg = Msg

posX : Float -> Float -> Float
posX angle len =
    50 + len * sin angle

posY : Float -> Float -> Float
posY angle len =
    50 - len * cos angle

drawNum : Int -> Svg Msg
drawNum num =
    let
        angle = 2 * pi  * num / 12
        len = 40
    in
        text'
            [ x (posX angle len |> toString)
            , y (posY angle len |> toString)
            ] [ text (toString num) ]

main = 
  div [] 
  [ h1 [] [ text "test" ]
  , svg []
  [ drawNum 3 ]
  ]
```

**Comment by jvoigtlaender** [comment]
Okay, that's completely different code, and the reason that the compiler is saying you are confusing `Int` and `Float` is because that's what you are doing. In `drawNum` you declare `num` to be an `Int`, but then multiply it with `pi`. You cannot multiply an `Int` with `pi`, because `pi` is a `Float`.

So what you have is a true type error in your code. It's not a bug of compiler or library.

I suggest to close the issue.

**Comment by rhetr** [comment]
thanks
